// <auto-generated />
using ApiFranquicia.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiFranquicia.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiFranquicia.Domain.MetroProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Precio");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("MetroProductos");
                });

            modelBuilder.Entity("ApiFranquicia.Domain.PlazaVeaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Precio");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("PlazaVeaProductos");
                });

            modelBuilder.Entity("ApiFranquicia.Domain.TottusProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Precio");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("TottusProductos");
                });

            modelBuilder.Entity("ApiFranquicia.Domain.WongProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Precio");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("WongProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
